
export interface RegisterUserType {
    _id: string | undefined,
    email: string,
    username: string,
    firstName: string,
    middleName?: string,
    lastName: string,
    role: 'ADMIN' | 'CONTRIBUTOR',
    password: string,
}

export type LoginType = {
    email: string
    password: string
}


export interface UserType {
    _id: string | undefined,
    email: string,
    username: string,
    firstName: string,
    middleName?: string,
    lastName: string,
    role: 'ADMIN' | 'CONTRIBUTOR',
    status: 'PENDING' | 'DECLINED' | 'APPROVED'
}

export interface FoodWasteType {
    _id?: string; // Optional, as it will be generated by MongoDB
    dateOfWaste: string; // Date of waste in string format (could be a date object based on your preference)
    foodCategory: string[]; // Array of food categories
    otherFoodCategory?: string; // Optional field for additional food category
    dishesWasted: string[]; // Array of dishes wasted
    otherDish?: string; // Optional field for additional dish
    quantity: number; // Quantity of waste in kg
    cost: number; // Cost associated with the waste
    reasonForWaste: string[]; // Array of reasons for waste
    otherReason?: string; // Optional field for additional reason
    notableIngredients?: string[]; // Optional array of notable ingredients
    otherIngredient?: string; // Optional field for additional ingredient
    temperature: string; // Temperature at which the food was stored
    mealType: string; // Type of meal (e.g., breakfast, lunch, dinner)
    wasteStage: string; // Stage of waste (e.g., production, consumption, disposal)
    disposalMethod: string; // Method of disposal
    otherDisposalMethod?: string; // Optional field for additional disposal method
    environmentalConditions?: string; // Optional environmental conditions during disposal
    relevantEvents?: string; // Optional field for any relevant events related to the waste
    additionalComments?: string; // Optional field for any additional comments
    userId?: UserType;
}